name: dart_ts_generator_example
description: Example models for dart_ts_generator

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  cloud_firestore: ^3.2.0
  json_annotation: ^4.11.0

dev_dependencies:
  dart_ts_generator:
    path: ../
  build_runner: ^2.13.1
  json_serializable: ^6.13.1
