targets:
  $default:
    builders:
      dart_ts_generator|dart_ts_file_builder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**/*.g.dart
            - lib/**/*.freezed.dart
        options:
          output_dir: "lib/generated/ts"
          file_suffix: ".g.ts"
          date_time_as_string: true
          include_base_classes: true

      dart_ts_generator|dart_ts_index_builder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**/*.g.dart
            - lib/**/*.freezed.dart
        options:
          output_dir: "lib/generated/ts"
          index_file: "index.ts"

builders:
  dart_ts_file_builder:
    import: "package:dart_ts_generator/builder.dart"
    builder_factories: ["dartTsFileBuilder"]
    build_extensions:
      ".dart": [".g.ts"]
    auto_apply: dependents
    build_to: source
    runs_before: []
    required_inputs: []
    applies_builders: []

  dart_ts_index_builder:
    import: "package:dart_ts_generator/index_builder.dart"
    builder_factories: ["tsIndexBuilder"]
    build_extensions:
      "$lib$": ["lib/generated/ts/index.ts"]
    auto_apply: dependents
    build_to: source
    runs_before: []
    is_optional: true